name: chatroom
version: 0.0.1
description: Dart chat app frontend
dependencies:
  browser: any
  polymer: '>=0.15.1 <0.16.0'
dev_dependencies:
  unittest: any
transformers:
- polymer:
    entry_points:
    - web/index.html
